### ISSUE TITLE
My avatar image does not appear on mobile

### ISSUE THREAD

**Issue by sylvaindev** [nickbalestra/kactus#13]
Hi,
My avatar image does not appear on the mobile device, he shows me a broken path , but it appears on the desktop .
Is there a solution to this problem ?
Sorry for my english.

http://sylvaindev.github.io/

**Comment by cjekel** [comment]
_Comments from main.js_

``` javascript
// To make images retina, add a class "2x" to the img element
// and add a <image-name>@2x.png image. Assumes jquery is loaded.
```

I noticed you [haven't uploaded a 2x image](https://github.com/sylvaindev/sylvaindev.github.io/blob/master/assets/images/avatar%402x.png). Additionally the blank image is a different extension than your original avatar (png vs jpg).

Just upload an _avatar@2x.jpg_ that is twice the resolution of your current _avatar.jpg_

You could also remove the class 2x from the img element, but that won't be needed if you just upload the 2x image.

**Comment by sylvaindev** [comment]
It works ! thank you a lot !
