### ISSUE TITLE
Disqus does not show up

### ISSUE THREAD

**Issue by ratulotron** [nickbalestra/kactus#3]
For some odd reason, Disquss comment box does not show up. First I tried to enable Disqus through _config.yml, then manually set the disqus short name in disqus.html template. Still doesn't work.

**Comment by nickbalestra** [comment]
Mmmm, No need to manually set the disqus short name in the include file. If it doesn't show up at all means that the include is not loaded,  have you enabled it on the layout? 

in `_layouts/post.html`

on the frontendmatters setting, be sure to have
`disqus: true`

**Comment by ratulotron** [comment]
The post.html portion is like this:

```
<!-- Disqus comments -->
{% if page.disqus %}
    <div class="archive readmore">
        <h3>Comments</h3>
        {% include disqus.html %}
    </div>
{% endif %}
```

I added a `disqus: true` in the default post: http://mnzr.github.io/welcome-to-jekyll/

**Comment by nickbalestra** [comment]
That link return a 404. Checked disqus and are working with a proper frontmatters ettings
